### ISSUE TITLE
Revolution Slider

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/premium-code#6]
@ineagu @rodica-andronache @selu91 

Avem o problema cu un client care nu a primit pluginul la cumpararea temei. Am intrat in contului si si intradevar pluginul nu apare in WordPress. 

Clientul asteapta sa razolvam problema? Aici este mail-ul lui: bert@train-it.nl

El ne spune ca asta este mailul cu care s-a inregistrat pe site si a cumparat tema deci ar trebui sa il gasim. 

Multumesc frumos. Va rog sa ma anuntati si pe mine.

**Comment by ineagu** [comment]
@mileamadalin il gasesti aici : https://secure.helpscout.net/conversation/70646230/13870/ . @claudiuvertistudio  poti sa il pui tu in tema ca si pe restul ?

**Comment by ineagu** [comment]
@Claudiu / @rodica poate adauga cineva asta ?
